pipeline {
    agent {
        label 'AGENT-1'
    }
    options{
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
        
    }
    // environment {
    //     DEBUG = 'true'
    // }

    parameters {
        choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'Select Action')
    }
    stages {
        stage('Init and Plan') {
            steps {
                withAWS(region: 'eu-west-1', credentials: 'aws-creds') {
                    sh """
                        cd 30-rds
                        terraform init -reconfigure
                        terraform plan -lock=false
                    """
                }
            }
        }

        stage('Apply or Destroy') {
            /* input {
                message "Should we continue to ${params.ACTION}"
                ok "Yes, we should."
            } */
            steps {
                withAWS(region: 'eu-west-1', credentials: 'aws-creds') {
                    sh """
                        cd 30-rds
                        if [ ${params.ACTION} == 'apply' ]
                        then
                            terraform apply -auto-approve -lock=false
                        elif [ ${params.ACTION} == 'destroy' ]
                        then
                            terraform destroy -auto-approve -lock=false
                        fi
                    """
                }
            }
        }
        

    }

    post {
        always{
            echo "This sections runs always"
            deleteDir()
        }
        success{
            echo "This section run when pipeline success"
        }
        failure{
            echo "This section run when pipeline failure"
        }
    }
}
